{{- if .Values.tableManager.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "loki.fullname" . }}-table-manager
  labels:
    {{- include "loki.labels" . | nindent 4 }}
    app.kubernetes.io/component: table-manager
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
  selector:
    {{- include "loki.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: table-manager
{{- end }}
