{{- with .Values.serviceMonitor -}}
  {{- if .enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "loki.distributorFullname" $ }}
  {{- with .namespace }}
  namespace: {{ . }}
  {{- end }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "loki.distributorLabels" $ | nindent 4 }}
    {{- toYaml .labels | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "loki.distributorSelectorLabels" $ | nindent 6 }}
  endpoints:
    - port: http
      {{- with .interval }}
      interval: {{ . }}
      {{- end }}
      {{- with .scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
{{- end }}
{{- end -}}
